# docker-compose.yml
version: '3.8'
services:
  store:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "12012:8080"
    environment:
      MYSQL_HOST: mysql  # Correctly points to the MySQL service
      MYSQL_PORT: 3306
      MYSQL_DATABASE: mysportsonlinestore
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysportsonlinestore
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./target:/usr/local/tomcat/webapps
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
